---
- name: Setup vollmed API on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
        force_apt_get: yes
        autoremove: yes

    - name: Reboot the system if required
      reboot:
        reboot_timeout: 3600
        test_command: /usr/bin/python3 -mplatform | grep -qi ubuntu

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - maven
        - openjdk-17-jre
        - docker.io
        - docker-compose

    - name: Create docker group
      group:
        name: docker
        state: present

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        append: yes
        groups: docker

    - name: Create MySQL service using docker-compose
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu/
        creates: /home/ubuntu/mysql_vollmed

    - name: Wait for MySQL service to start
      wait_for:
        host: localhost
        port: 3306
        state: started
        timeout: 60

    - name: Grant privileges to vollmed user
      command: >
        docker exec {{ item }} mysql -u root -p -e "GRANT ALL PRIVILEGES ON *.* TO 'vollmed'@'%';"
      args:
        executable: /bin/bash
        chdir: /home/ubuntu/
      with_items:
        - "{{ lookup('pipe', 'docker ps --filter name=db --format {{.ID}}') }}"

    - name: Create vollmed_api_test database
      command: >
        docker exec {{ item }} mysql -u root -p -e "CREATE DATABASE vollmed_api_test;"
      args:
        executable: /bin/bash
        chdir: /home/ubuntu/
      with_items:
        - "{{ lookup('pipe', 'docker ps --filter name=db --format {{.ID}}') }}"

    - name: Clone vollmed API git repo
      git:
        repo: https://github.com/santos-adilio/DevOpsChallenge2023.git
        dest: /home/ubuntu/DevOpsChallenge2023

    - name: Build the vollmed API using Maven
      command: mvn clean package -DskipTests
      args:
        chdir: /home/ubuntu/DevOpsChallenge2023

    - name: Run the vollmed API
      command: java -jar -DDATASOURCE_URL=jdbc:mysql://localhost/vollmed_api -DDATASOURCE_USERNAME=vollmed -DDATASOURCE_PASSWORD=p^IMJ2D-iWQ^Jf= /home/ubuntu/DevOpsChallenge2023/target/api-0.0.1-SNAPSHOT.jar -Dspring.profiles.active=prod
      args:
        chdir: /home/ubuntu/DevOpsChallenge2023
